---
- hosts: puppet
  gather_facts: False
  become: true
  become_user: root
  vars:
    - packages: ["git" , "docker.io"]
  tasks:
    - name: Installing {{ packages }} on {{ hostname }}
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"